-- Supabase SQL migration for Prayonit tracked-link Layer 2.
-- Apply manually via the Supabase SQL editor or `supabase db push`.
-- This does not run automatically as part of the Python automation.

create table if not exists social_tracking_links (
    tracking_id text primary key,
    created_at timestamptz default now(),
    run_id text,
    campaign_name text,
    formula_name text,
    persona_name text,
    platform text,
    post_type text,
    slot text,
    destination text,
    scheduled_at timestamptz
);

create table if not exists social_tracking_clicks (
    id bigint generated by default as identity primary key,
    tracking_id text,
    clicked_at timestamptz default now(),
    platform text,
    destination text,
    user_agent text,
    referrer text
);

create index if not exists idx_social_tracking_clicks_tracking_id
    on social_tracking_clicks (tracking_id);
